package guiCourtReservation;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @authors Abhishek Balaraman; António Queirós; Paulo Garcez Vieira
 * Master of Applied Computer Science
 * Applied Software Engineering 2015/2016
 * ESTGOH - IPC
 * 
 * Tennis Club Reservation System Software
 * 
 */
public class jTennisCourtReservation extends javax.swing.JFrame {

    /**
     * Creates new form jTennisCourtReservation
     */
    public jTennisCourtReservation() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMyDesktopPane = new javax.swing.JDesktopPane();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniExit = new javax.swing.JMenuItem();
        mnuReservations = new javax.swing.JMenu();
        mniMakeReserv = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniCancelReserv = new javax.swing.JMenuItem();
        mnuManage = new javax.swing.JMenu();
        mniMngMembers = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniMngCourts = new javax.swing.JMenuItem();
        mniMngTimetable = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniMngDates = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        mniPresSchedule = new javax.swing.JMenuItem();
        mniPresReservations = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniPresOccupation = new javax.swing.JMenuItem();
        mnuShow = new javax.swing.JMenu();
        mniMemberReservation = new javax.swing.JMenuItem();
        mniCourtSchedule = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mniHlpAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tennis Court Reservation");
        setAlwaysOnTop(true);
        setName("winPrincipal"); // NOI18N
        setResizable(false);

        javax.swing.GroupLayout jMyDesktopPaneLayout = new javax.swing.GroupLayout(jMyDesktopPane);
        jMyDesktopPane.setLayout(jMyDesktopPaneLayout);
        jMyDesktopPaneLayout.setHorizontalGroup(
            jMyDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        jMyDesktopPaneLayout.setVerticalGroup(
            jMyDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );

        mnuFile.setText("File");

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        mnuPrincipal.add(mnuFile);

        mnuReservations.setText("Reservations");

        mniMakeReserv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        mniMakeReserv.setText("Make");
        mniMakeReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMakeReservActionPerformed(evt);
            }
        });
        mnuReservations.add(mniMakeReserv);
        mnuReservations.add(jSeparator1);

        mniCancelReserv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mniCancelReserv.setText("Cancel");
        mniCancelReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCancelReservActionPerformed(evt);
            }
        });
        mnuReservations.add(mniCancelReserv);

        mnuPrincipal.add(mnuReservations);

        mnuManage.setText("Manage");

        mniMngMembers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        mniMngMembers.setText("Members");
        mniMngMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMngMembersActionPerformed(evt);
            }
        });
        mnuManage.add(mniMngMembers);
        mnuManage.add(jSeparator2);

        mniMngCourts.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        mniMngCourts.setText("Courts");
        mniMngCourts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMngCourtsActionPerformed(evt);
            }
        });
        mnuManage.add(mniMngCourts);

        mniMngTimetable.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        mniMngTimetable.setText("Timetable");
        mniMngTimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMngTimetableActionPerformed(evt);
            }
        });
        mnuManage.add(mniMngTimetable);
        mnuManage.add(jSeparator4);

        mniMngDates.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        mniMngDates.setText("Dates");
        mniMngDates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMngDatesActionPerformed(evt);
            }
        });
        mnuManage.add(mniMngDates);

        mnuPrincipal.add(mnuManage);

        mnuReports.setText("Reports");

        mniPresSchedule.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniPresSchedule.setText("Schedule");
        mniPresSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPresScheduleActionPerformed(evt);
            }
        });
        mnuReports.add(mniPresSchedule);

        mniPresReservations.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniPresReservations.setText("Reservations");
        mniPresReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPresReservationsActionPerformed(evt);
            }
        });
        mnuReports.add(mniPresReservations);
        mnuReports.add(jSeparator3);

        mniPresOccupation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniPresOccupation.setText("Occupation");
        mniPresOccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPresOccupationActionPerformed(evt);
            }
        });
        mnuReports.add(mniPresOccupation);

        mnuPrincipal.add(mnuReports);

        mnuShow.setText(" Show  Schedule");

        mniMemberReservation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniMemberReservation.setText("Members");
        mniMemberReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMemberReservationActionPerformed(evt);
            }
        });
        mnuShow.add(mniMemberReservation);

        mniCourtSchedule.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniCourtSchedule.setText("Courts");
        mniCourtSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCourtScheduleActionPerformed(evt);
            }
        });
        mnuShow.add(mniCourtSchedule);

        mnuPrincipal.add(mnuShow);

        mnuHelp.setText("Help");

        mniHlpAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mniHlpAbout.setText("About");
        mniHlpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHlpAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mniHlpAbout);

        mnuPrincipal.add(mnuHelp);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMyDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMyDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniCancelReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCancelReservActionPerformed
        winCancelReservation intframeCancelReservation = new winCancelReservation();
        jMyDesktopPane.add(intframeCancelReservation);
        intframeCancelReservation.show();
    }//GEN-LAST:event_mniCancelReservActionPerformed

    private void mniMngCourtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMngCourtsActionPerformed
        winCourts intframeCourts = new winCourts();
        jMyDesktopPane.add(intframeCourts);
        intframeCourts.show();
    }//GEN-LAST:event_mniMngCourtsActionPerformed

    private void mniPresReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPresReservationsActionPerformed
        winPresMemberReserves intPresMemberReserves = new winPresMemberReserves();
        jMyDesktopPane.add(intPresMemberReserves);
        intPresMemberReserves.show();
    }//GEN-LAST:event_mniPresReservationsActionPerformed

    private void mniMakeReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMakeReservActionPerformed
        winMakeReservation intframeMakeReserv = new winMakeReservation();
        jMyDesktopPane.add(intframeMakeReserv);
        intframeMakeReserv.show();
    }//GEN-LAST:event_mniMakeReservActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniMngMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMngMembersActionPerformed
        winMembers intframeMembers = new winMembers();
        jMyDesktopPane.add(intframeMembers);
        intframeMembers.show();
    }//GEN-LAST:event_mniMngMembersActionPerformed

    private void mniHlpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHlpAboutActionPerformed
        jAbout about = new jAbout();
        about.setVisible(true);
    }//GEN-LAST:event_mniHlpAboutActionPerformed

    private void mniMngTimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMngTimetableActionPerformed
        winTimetable intframeTimetable = new winTimetable();
        jMyDesktopPane.add(intframeTimetable);
        intframeTimetable.show();
    }//GEN-LAST:event_mniMngTimetableActionPerformed

    private void mniMngDatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMngDatesActionPerformed
        winDates intframeDates = new winDates();
        jMyDesktopPane.add(intframeDates);
        intframeDates.show();
    }//GEN-LAST:event_mniMngDatesActionPerformed

    private void mniPresScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPresScheduleActionPerformed
        winPresSchedule intPresSchedule = new winPresSchedule();
        jMyDesktopPane.add(intPresSchedule);
        intPresSchedule.show();
    }//GEN-LAST:event_mniPresScheduleActionPerformed

    private void mniPresOccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPresOccupationActionPerformed
        winPresOccupation intPresOccupation = new winPresOccupation();
        jMyDesktopPane.add(intPresOccupation);
        intPresOccupation.show();
    }//GEN-LAST:event_mniPresOccupationActionPerformed

    private void mniCourtScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCourtScheduleActionPerformed
        winCourtSchedule intCourtSchedule = new winCourtSchedule();
        jMyDesktopPane.add(intCourtSchedule);
        intCourtSchedule.show();
    }//GEN-LAST:event_mniCourtScheduleActionPerformed

    private void mniMemberReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMemberReservationActionPerformed
        winMemberReservation intMemberReservation = new winMemberReservation();
        jMyDesktopPane.add(intMemberReservation);
        intMemberReservation.show();
    }//GEN-LAST:event_mniMemberReservationActionPerformed

      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jMyDesktopPane;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem mniCancelReserv;
    private javax.swing.JMenuItem mniCourtSchedule;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniHlpAbout;
    private javax.swing.JMenuItem mniMakeReserv;
    private javax.swing.JMenuItem mniMemberReservation;
    private javax.swing.JMenuItem mniMngCourts;
    private javax.swing.JMenuItem mniMngDates;
    private javax.swing.JMenuItem mniMngMembers;
    private javax.swing.JMenuItem mniMngTimetable;
    private javax.swing.JMenuItem mniPresOccupation;
    private javax.swing.JMenuItem mniPresReservations;
    private javax.swing.JMenuItem mniPresSchedule;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuManage;
    private javax.swing.JMenuBar mnuPrincipal;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenu mnuReservations;
    private javax.swing.JMenu mnuShow;
    // End of variables declaration//GEN-END:variables
}