/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiCourtReservation;

import domainCourtReservation.enumErrorCode;
import domainCourtReservation.enumEventOrigin;
import domainCourtReservation.enumEventType;
import domainCourtReservation.enumReservationStatus;
import domainCourtReservation.jReservations;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulo Garcez Vieira
 */
public class winCancelReservation extends javax.swing.JInternalFrame {
    
    private Date dateReserv;
    private int index;
    
    /**
     * Creates new form winCancelReservation
     */
    public winCancelReservation() {
        initComponents();
        this.btnCancel.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDate = new javax.swing.JLabel();
        jXDatePickerFrom = new org.jdesktop.swingx.JXDatePicker();
        lblHour = new javax.swing.JLabel();
        spnHour = new javax.swing.JSpinner();
        lblCourt = new javax.swing.JLabel();
        txtCourt = new javax.swing.JTextField();
        lblMember = new javax.swing.JLabel();
        txtMember = new javax.swing.JTextField();
        lblEventType = new javax.swing.JLabel();
        txtEventType = new javax.swing.JTextField();
        lblEventOrigin = new javax.swing.JLabel();
        txtEventOrigin = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setClosable(true);

        lblDate.setText("Date");

        jXDatePickerFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePickerFromActionPerformed(evt);
            }
        });

        lblHour.setText("Hour");

        spnHour.setModel(new javax.swing.SpinnerListModel(new String[] {"00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00"}));

        lblCourt.setText("Court ID");

        txtCourt.setEnabled(false);

        lblMember.setText("Member ID");

        txtMember.setEnabled(false);

        lblEventType.setText("Type");

        txtEventType.setToolTipText("");
        txtEventType.setEnabled(false);

        lblEventOrigin.setText("Origin");

        txtEventOrigin.setEnabled(false);

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblStatus.setText("Status");

        txtStatus.setEnabled(false);

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEventOrigin)
                    .addComponent(lblCourt)
                    .addComponent(lblEventType)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEventOrigin)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCourt)
                        .addGap(64, 64, 64)
                        .addComponent(lblMember)
                        .addGap(18, 18, 18)
                        .addComponent(txtMember, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEventType)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXDatePickerFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnHour, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(jXDatePickerFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHour)
                    .addComponent(spnHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourt)
                    .addComponent(txtCourt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMember)
                    .addComponent(txtMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEventType)
                    .addComponent(txtEventType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEventOrigin)
                    .addComponent(txtEventOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnCancel))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXDatePickerFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePickerFromActionPerformed
        try {
            this.dateReserv = this.jXDatePickerFrom.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String strDateReserv = sdf.format(this.dateReserv);
            this.jXDatePickerFrom.setFormats(new SimpleDateFormat("dd-MM-yyyy"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error entering date! " + e);}
    }//GEN-LAST:event_jXDatePickerFromActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String strHour = (String) this.spnHour.getValue();
        index = jReservations.findReservation(dateReserv, strHour);
        if (index != -1) {
            jReservations reserv = jReservations.getReservation(index);
            this.txtCourt.setText(Integer.toString(reserv.courtID));
            this.txtMember.setText(Integer.toString(reserv.memberID));
            String tmp1 = reserv.eventType.name();
            String tmp2 = reserv.eventOrigin.name();
            String tmp3 = reserv.status.name();
            this.txtEventType.setText(tmp1);
            this.txtEventOrigin.setText(tmp2);
            this.txtStatus.setText(tmp3);
            this.btnCancel.setEnabled(true);
            this.btnFind.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this,"Reservation not found! ");
        }                  
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        enumErrorCode err = jReservations.cancelReservation(index);
        if (err == enumErrorCode.OK) {
            JOptionPane.showMessageDialog(this,"Reservation canceled with sucess! ");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,"Reservation not canceled! ");
        }  
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerFrom;
    private javax.swing.JLabel lblCourt;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEventOrigin;
    private javax.swing.JLabel lblEventType;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblMember;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JSpinner spnHour;
    private javax.swing.JTextField txtCourt;
    private javax.swing.JTextField txtEventOrigin;
    private javax.swing.JTextField txtEventType;
    private javax.swing.JTextField txtMember;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
