package guiCourtReservation;

import domainCourtReservation.enumSurface;
import domainCourtReservation.enumErrorCode;
import domainCourtReservation.jCourt;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Paulo Garcez Vieira
 */
public class winCourts extends javax.swing.JInternalFrame {

    /**
     * Creates new form winCourts
     */
    public winCourts() {
        initComponents();
        this.cmbLocation.setSelectedIndex(-1);
        this.cmbSurface.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mybuttonGroup = new javax.swing.ButtonGroup();
        lblCourtID = new javax.swing.JLabel();
        txtCourtID = new javax.swing.JTextField();
        lblSurface = new javax.swing.JLabel();
        cmbSurface = new javax.swing.JComboBox<>();
        lblLocation = new javax.swing.JLabel();
        cmbLocation = new javax.swing.JComboBox<>();
        lblLightning = new javax.swing.JLabel();
        chkLightning = new javax.swing.JCheckBox();
        radEnableCourt = new javax.swing.JRadioButton();
        radDisableCourt = new javax.swing.JRadioButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();

        setClosable(true);

        lblCourtID.setText("Court ID");

        lblSurface.setText("Surface");
        lblSurface.setEnabled(false);

        cmbSurface.setModel(new DefaultComboBoxModel(enumSurface.values()));
        cmbSurface.setEnabled(false);
        /*cmbSurface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSurfaceActionPerformed(evt);
            }
        });*/

        lblLocation.setText("Location");
        lblLocation.setEnabled(false);

        cmbLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDOOR", "OUTDOOR" }));
        cmbLocation.setSelectedIndex(-1);
        cmbLocation.setToolTipText("");
        cmbLocation.setEnabled(false);
        /*cmbLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLocationActionPerformed(evt);
            }
        });*/

        lblLightning.setText("Lighting");
        lblLightning.setEnabled(false);

        chkLightning.setEnabled(false);
        /*chkLightning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLightningActionPerformed(evt);
            }
        });*/

        mybuttonGroup.add(radEnableCourt);
        radEnableCourt.setSelected(true);
        radEnableCourt.setText("Enable");
        radEnableCourt.setEnabled(false);
        /*radEnableCourt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radEnableCourtActionPerformed(evt);
            }
        });*/

        mybuttonGroup.add(radDisableCourt);
        radDisableCourt.setText("Disable");
        radDisableCourt.setEnabled(false);

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.setEnabled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLocation)
                                .addGap(18, 18, 18)
                                .addComponent(cmbLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSurface)
                                .addGap(22, 22, 22)
                                .addComponent(cmbSurface, 0, 356, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCourtID)
                                .addGap(18, 18, 18)
                                .addComponent(txtCourtID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnFind)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNew)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLightning)
                                .addGap(18, 18, 18)
                                .addComponent(chkLightning)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radEnableCourt)
                                .addGap(18, 18, 18)
                                .addComponent(radDisableCourt)))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourtID)
                    .addComponent(txtCourtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind)
                    .addComponent(btnNew))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurface)
                    .addComponent(cmbSurface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocation)
                    .addComponent(cmbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLightning)
                        .addComponent(chkLightning))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radEnableCourt)
                        .addComponent(radDisableCourt)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnClear)
                    .addComponent(btnDelete)
                    .addComponent(btnSave))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String str = this.txtCourtID.getText();
        try {
                int k = Integer.valueOf(str);
                int j = jCourt.findCourt(k);
                enumErrorCode errCode =  jCourt.deleteCourt(j);
                if (errCode == enumErrorCode.OK) {
                JOptionPane.showMessageDialog(this,"Court removed with success!");
                } else {
                    JOptionPane.showMessageDialog(this,"Court not removed!");
                }  
        } catch (NumberFormatException e) { 
            JOptionPane.showMessageDialog(this,"Court not removed! " + e);}
        this.resetComponents();
    }//GEN-LAST:event_btnDeleteActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
         String str = this.txtCourtID.getText();
         try {
            int k = Integer.valueOf(str);
            int j = jCourt.findCourt(k);
            if (j >= 0) {
                this.txtCourtID.setText(Integer.toString(jCourt.getCourtID(j)));
                this.cmbSurface.setSelectedItem(jCourt.getSurface(j));
                this.cmbLocation.setSelectedItem(jCourt.getLocation(j));
                this.chkLightning.setSelected(jCourt.getLighting(j));
                if (jCourt.getEnable(j)) {
                    this.radEnableCourt.setSelected(true);
                    this.radDisableCourt.setSelected(false);
                } else {
                    this.radEnableCourt.setSelected(false);
                    this.radDisableCourt.setSelected(true);
                }
                    this.lblSurface.setEnabled(true);
                    this.cmbSurface.setEnabled(true);
                    this.lblLocation.setEnabled(true);
                    this.cmbLocation.setEnabled(true);
                    this.lblLightning.setEnabled(true);
                    this.chkLightning.setEnabled(true);
                    this.radEnableCourt.setEnabled(true);
                    this.radDisableCourt.setEnabled(true);
                    this.btnSave.setEnabled(true);
                    this.btnFind.setEnabled(false);
                    this.btnNew.setEnabled(false);
                    this.btnDelete.setEnabled(true);
                    this.lblCourtID.setEnabled(false);
                    this.txtCourtID.setEnabled(false);
                    this.btnSave.setEnabled(true);
                    this.btnClear.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this,"Court not found!");
            }  
         } catch (NumberFormatException e) { 
           JOptionPane.showMessageDialog(this,"Please enter valid n.º Court ID!");}     
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
            this.resetComponents();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         String str = this.txtCourtID.getText();
         enumErrorCode errCode;
         try {
                int k = Integer.valueOf(str);
                int j = jCourt.findCourt(k);
                int tempInt = k;
                enumSurface tempEnum = (enumSurface) this.cmbSurface.getSelectedItem();
                String tempStr = (String) this.cmbLocation.getSelectedItem();
                boolean tempLight = this.chkLightning.isSelected();
                boolean tempEnable = false;
                if (this.radEnableCourt.isSelected()) tempEnable = true;
                jCourt temp = new jCourt(k, tempEnum, tempStr, tempLight, tempEnable);
                errCode = jCourt.saveCourt(j, temp);
                if (errCode == enumErrorCode.OK) {
                    JOptionPane.showMessageDialog(this,"Court saved with success!");
                    this.resetComponents();
                } else {
                        if (errCode == enumErrorCode.INF_INVALID) {
                            JOptionPane.showMessageDialog(this,"Please enter valid court details!");
                        } else {
                            JOptionPane.showMessageDialog(this,"Court not saved! ");
                            this.resetComponents();
                        }
                }               
         } catch (NumberFormatException e) { 
            JOptionPane.showMessageDialog(this,"Court not saved! " + e);}   
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        String str = this.txtCourtID.getText();
        try {
            int k = Integer.valueOf(str);
            int j = jCourt.findCourt(k);
            if (j != -1) {
                JOptionPane.showMessageDialog(this,"CourtID already exists!");
            } else {
                this.lblSurface.setEnabled(true);
                this.cmbSurface.setEnabled(true);
                this.lblLocation.setEnabled(true);
                this.cmbLocation.setEnabled(true);
                this.lblLightning.setEnabled(true);
                this.chkLightning.setEnabled(true);
                this.radEnableCourt.setEnabled(true);
                this.radDisableCourt.setEnabled(true);
                this.btnSave.setEnabled(true);
                this.btnFind.setEnabled(false);
                this.btnNew.setEnabled(false);
                this.lblCourtID.setEnabled(false);
                this.txtCourtID.setEnabled(false);
                this.btnSave.setEnabled(true);
                this.btnClear.setEnabled(true);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Please enter valid n.º Court ID!");}            
    }//GEN-LAST:event_btnNewActionPerformed

    private void resetComponents() {
        this.btnCancel.setEnabled(true);
        this.btnDelete.setEnabled(false);
        this.btnClear.setEnabled(false);
        this.btnFind.setEnabled(true);
        this.btnNew.setEnabled(true);
        this.btnSave.setEnabled(false);
        this.chkLightning.setSelected(false);
        this.chkLightning.setEnabled(false);
        this.cmbLocation.setEnabled(false);
        this.cmbLocation.setSelectedIndex(-1);
        this.cmbSurface.setEnabled(false);
        this.cmbSurface.setSelectedIndex(-1);
        this.lblCourtID.setEnabled(true);
        this.lblLightning.setEnabled(false);
        this.lblLocation.setEnabled(false);
        this.lblSurface.setEnabled(false);
        this.radDisableCourt.setEnabled(false);
        this.radEnableCourt.setEnabled(false);
        this.txtCourtID.setText("");
        this.txtCourtID.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkLightning;
    private javax.swing.JComboBox<String> cmbLocation;
    private javax.swing.JComboBox<String> cmbSurface;
    private javax.swing.JLabel lblCourtID;
    private javax.swing.JLabel lblLightning;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblSurface;
    private javax.swing.ButtonGroup mybuttonGroup;
    private javax.swing.JRadioButton radDisableCourt;
    private javax.swing.JRadioButton radEnableCourt;
    private javax.swing.JTextField txtCourtID;
    // End of variables declaration//GEN-END:variables

}
