/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiCourtReservation;

import domainCourtReservation.enumSurface;
import domainCourtReservation.enumErrorCode;
import domainCourtReservation.jMember;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulo Garcez Vieira
 */
public class winMembers extends javax.swing.JInternalFrame {

    /**
     * Creates new form winMembers
     */
    public winMembers() {
        initComponents();
        this.cmbSurface.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupStatus = new javax.swing.ButtonGroup();
        lblMemberID = new javax.swing.JLabel();
        txtMemberID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblSurface = new javax.swing.JLabel();
        cmbSurface = new javax.swing.JComboBox<>();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        radStatusActive = new javax.swing.JRadioButton();
        radStatusInactive = new javax.swing.JRadioButton();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setClosable(true);

        lblMemberID.setText("Member ID");

        /*txtMemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberIDActionPerformed(evt);
            }
        });*/

        lblName.setText("Name");
        lblName.setEnabled(false);

        txtName.setEnabled(false);

        lblSurface.setText("Court Preference");
        lblSurface.setEnabled(false);

        cmbSurface.setModel(new DefaultComboBoxModel(enumSurface.values()));
        cmbSurface.setEnabled(false);
        /*cmbSurface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSurfaceActionPerformed(evt);
            }
        });*/

        lblEmail.setText("Email");
        lblEmail.setEnabled(false);

        txtEmail.setEnabled(false);
        /*txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });*/

        lblPassword.setText("Password");
        lblPassword.setEnabled(false);

        txtPassword.setEnabled(false);
        /*txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });*/

        buttonGroupStatus.add(radStatusActive);
        radStatusActive.setSelected(true);
        radStatusActive.setText("Active");
        radStatusActive.setEnabled(false);
        /*radStatusActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radStatusActiveActionPerformed(evt);
            }
        });*/

        buttonGroupStatus.add(radStatusInactive);
        radStatusInactive.setText("Inactive");
        radStatusInactive.setEnabled(false);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.setEnabled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMemberID)
                            .addComponent(lblName)
                            .addComponent(lblSurface)
                            .addComponent(lblEmail)
                            .addComponent(lblPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(radStatusActive)
                                .addGap(89, 89, 89))
                            .addComponent(txtEmail)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnFind)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNew)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbSurface, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radStatusInactive)
                            .addComponent(btnCancel))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMemberID)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFind)
                            .addComponent(btnNew))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurface)
                    .addComponent(cmbSurface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radStatusInactive)
                    .addComponent(radStatusActive))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)
                    .addComponent(btnClear))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String str = this.txtMemberID.getText();
        enumErrorCode errCode;
        try {
            int k = Integer.valueOf(str);
            int j = jMember.findMember(k);
            int tempInt = k;
            String tempName = this.txtName.getText();
            enumSurface tempEnum = (enumSurface) this.cmbSurface.getSelectedItem();
            String tempEmail = this.txtEmail.getText();
            String tempPass = this.txtPassword.getText();
            boolean tempStatus = false;
            if (this.radStatusActive.isSelected()) tempStatus = true;
            jMember temp = new jMember(k, tempName, tempEnum, tempEmail, tempPass, tempStatus);
            errCode = jMember.saveMember(j, temp);
            if (errCode == enumErrorCode.OK) {
                JOptionPane.showMessageDialog(this,"Member saved with success!");
		this.resetComponents();
            } else {
                if (errCode == enumErrorCode.INF_INVALID) {
                    JOptionPane.showMessageDialog(this,"Please enter valid member details!");
		} else {
                    JOptionPane.showMessageDialog(this,"Member not saved!");
                    this.resetComponents();
		}
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Member not saved! " + e);}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String str = this.txtMemberID.getText();
        try {
            int k = Integer.valueOf(str);
            int j = jMember.findMember(k);
            enumErrorCode errCode = jMember.deleteMember(j); 
            if (errCode == enumErrorCode.OK) {
                JOptionPane.showMessageDialog(this,"Member removed with success!");
            } else {
                JOptionPane.showMessageDialog(this,"Member not removed!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Member not removed! " + e);}
            this.resetComponents();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String str = this.txtMemberID.getText();
        try {
            int k = Integer.valueOf(str);
            int j = jMember.findMember(k);
            if (j >= 0) {
                this.txtMemberID.setText(Integer.toString(jMember.getMemberID(j)));
                this.txtName.setText(jMember.getName(j));
                this.cmbSurface.setSelectedItem(jMember.getSurface(j));
                this.txtEmail.setText(jMember.getEmail(j));
                this.txtPassword.setText(jMember.getPassword(j));
                if (jMember.getStatus(j)) {
                    this.radStatusActive.setSelected(true);
                    this.radStatusInactive.setSelected(false);
                } else {
                    this.radStatusActive.setSelected(false);
                    this.radStatusInactive.setSelected(true);
                }
                this.lblName.setEnabled(true);
                this.txtName.setEnabled(true);
                this.lblSurface.setEnabled(true);
                this.cmbSurface.setEnabled(true);
                this.lblEmail.setEnabled(true);
                this.txtEmail.setEnabled(true);
                this.lblPassword.setEnabled(true);
                this.txtPassword.setEnabled(true);
                this.radStatusActive.setEnabled(true);
                this.radStatusInactive.setEnabled(true);
                this.btnSave.setEnabled(true);
                this.btnFind.setEnabled(false);
                this.btnNew.setEnabled(false);
                this.lblMemberID.setEnabled(false);
                this.txtMemberID.setEnabled(false);
                this.btnSave.setEnabled(true);
                this.btnClear.setEnabled(true);
                this.btnDelete.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this,"Member not found!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Please enter valid n.º Member ID!");}
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        String str = this.txtMemberID.getText();
        try {
            int k = Integer.valueOf(str);
            int j = jMember.findMember(k);
            if (j != -1) {
                JOptionPane.showMessageDialog(this,"Member ID already exists!");
            } else {
                this.lblName.setEnabled(true);
                this.txtName.setEnabled(true);
                this.lblSurface.setEnabled(true);
                this.cmbSurface.setEnabled(true);
                this.lblEmail.setEnabled(true);
                this.txtEmail.setEnabled(true);
                this.lblPassword.setEnabled(true);
                this.txtPassword.setEnabled(true);
                this.radStatusActive.setEnabled(true);
                this.radStatusInactive.setEnabled(true);
                this.btnSave.setEnabled(true);
                this.btnFind.setEnabled(false);
                this.btnNew.setEnabled(false);
                this.lblMemberID.setEnabled(false);
                this.txtMemberID.setEnabled(false);
                this.btnSave.setEnabled(true);
                this.btnClear.setEnabled(true);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Please enter valid n.º Member ID!");}    
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        this.resetComponents();
    }//GEN-LAST:event_btnClearActionPerformed

    private void resetComponents() {
        this.btnCancel.setEnabled(true);
        this.btnDelete.setEnabled(false);
        this.btnClear.setEnabled(false);
        this.btnFind.setEnabled(true);
        this.btnNew.setEnabled(true);
        this.btnSave.setEnabled(false);
        this.lblMemberID.setEnabled(true);
        this.txtMemberID.setText("");
        this.txtMemberID.setEnabled(true);
        this.lblName.setEnabled(false);
        this.txtName.setText("");
        this.txtName.setEnabled(false);
        this.lblSurface.setEnabled(false);
        this.cmbSurface.setSelectedIndex(-1);
        this.cmbSurface.setEnabled(false);
        this.lblEmail.setEnabled(false);
        this.txtEmail.setText("");
        this.txtEmail.setEnabled(false);
        this.lblPassword.setEnabled(false);
        this.txtPassword.setText("");
        this.txtPassword.setEnabled(false);
        this.radStatusActive.setEnabled(false);
        this.radStatusInactive.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroupStatus;
    private javax.swing.JComboBox<String> cmbSurface;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMemberID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSurface;
    private javax.swing.JRadioButton radStatusActive;
    private javax.swing.JRadioButton radStatusInactive;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMemberID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
