/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiCourtReservation;

import domainCourtReservation.jCourt;
import domainCourtReservation.jReservations;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulo Garcez Vieira
 */
public class winPresSchedule extends javax.swing.JInternalFrame {

    /**
     * Creates new form winPresSchedule
     */
    public winPresSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        cmbCourtID = new javax.swing.JComboBox<>();
        jMyScrollPane = new javax.swing.JScrollPane();
        jMyTextArea = new javax.swing.JTextArea();
        btnFind = new javax.swing.JButton();
        lblCourtID = new javax.swing.JLabel();
        lblFromDate = new javax.swing.JLabel();
        jXDatePickerFrom = new org.jdesktop.swingx.JXDatePicker();

        setClosable(true);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        cmbCourtID.setModel(new DefaultComboBoxModel(jCourt.getCourtsID()));
        cmbCourtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCourtIDActionPerformed(evt);
            }
        });

        jMyTextArea.setColumns(20);
        jMyTextArea.setRows(5);
        jMyTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jMyScrollPane.setViewportView(jMyTextArea);

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        lblCourtID.setText("Court ID");

        lblFromDate.setText("Date");

        jXDatePickerFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePickerFromActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCourtID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbCourtID, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lblFromDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXDatePickerFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jMyScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFind)
                    .addComponent(lblCourtID)
                    .addComponent(cmbCourtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFromDate)
                    .addComponent(jXDatePickerFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jMyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private Date dateFrom;
    private final static String newline = "\n";
    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void cmbCourtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCourtIDActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String str = (String) this.cmbCourtID.getSelectedItem();
        String[] courtReservations = new String[100];
        int k = -1;
        try {
            k = Integer.valueOf(str);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Please enter valid n.º Court ID!");}
        if (k != -1) { courtReservations = jReservations.presentCourtReservations(k, this.dateFrom); }
        if (courtReservations.length > 0) {
            String text = jMyTextArea.getText();
            for (int m = 0; m < courtReservations.length; m++) {
                if (courtReservations[m]!=null) {
                    jMyTextArea.append(courtReservations[m] + newline);
                }
            }
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void jXDatePickerFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePickerFromActionPerformed
        try {
            this.dateFrom = this.jXDatePickerFrom.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String strfromDate = sdf.format(this.dateFrom);
            this.jXDatePickerFrom.setFormats(new SimpleDateFormat("dd-MM-yyyy"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error entering date! " + e);}
    }//GEN-LAST:event_jXDatePickerFromActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JComboBox<String> cmbCourtID;
    private javax.swing.JScrollPane jMyScrollPane;
    private javax.swing.JTextArea jMyTextArea;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerFrom;
    private javax.swing.JLabel lblCourtID;
    private javax.swing.JLabel lblFromDate;
    // End of variables declaration//GEN-END:variables
}
